#!/usr/bin/env sh
swaymsg output '*' bg $(find $1 -type f | shuf -n1) fill
#OLD_PID=$!
while true; do
    sleep 600
    swaymsg output '*' bg $(find $1 -type f | shuf -n1) fill
 #   swaybg -i $(find img/. -type f | shuf -n1) -m fill &
  #  NEXT_PID=$!
    sleep 5
   3 kill $OLD_PID
    #OLD_PID=$NEXT_PID
done
