# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '#1a1c1e'
    foreground: '#e3e2e6'

  # Normal colors
  normal:
    black: '#000000'
    red: '#EA6C73'
    green: '#ffffff'
    yellow: '#F9AF4F'
    blue: '#53BDFA'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'
